---
title: "Survival Analysis Post"
output: md_document
date: "2025-02-24"
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, survival, patchwork, minpack.lm, DT)

```

```{r data}

url <- "https://docs.google.com/spreadsheets/d/1L5AxjLZdCqSKOZEfRCFpV8iN5eDYxnE7t8sbRvfFRSQ/export?format=csv&gid=664667008"
telco_churn <- read_csv(url) |> mutate(Churn = ifelse(Churn == "Yes", 1, 0))

```

```{r explore}

# Kaplan-Meier Overall
mod.km <- survfit(Surv(tenure, Churn) ~ 1, data = telco_churn)
km_df <- data.frame(tenure = mod.km$time, km_fit = mod.km$surv)
ggplot(km_df, aes(x = tenure, y = km_fit)) +
  geom_step(color = 'steelblue') +
  ylim(0, NA) +
  labs(x = "Tenure", y = "Survival Probability", title = "Telco Survival % By Tenure") +
  theme_minimal()

```

```{r parametric_models}

km_df_12 <- km_df |> filter(tenure <= 12) # fit on only 12 months of tenure
weibull_fit <- nlsLM(km_fit ~ exp(- (lambda * tenure) ^ kappa), data = km_df_12, start = list(lambda = 0.01, kappa = 1))
loglogistic_fit <- nlsLM(km_fit ~ 1 / (1 + (lambda * tenure) ^ kappa), data = km_df_12, start = list(lambda = 0.01, kappa = 1))
exp_fit <- nlsLM(km_fit ~ exp(-lambda * tenure), data = km_df_12, start = list(lambda = 0.01))
wei_exp_fit <- nlsLM(km_fit ~ p * exp(-lambda_e * tenure) + (1 - p) * exp(- (lambda_w * tenure) ^ kappa_w), data = km_df_12, 
                         start = list(lambda_e = 0.01, lambda_w = 0.01, kappa_w = 1, p = 0.5), control = nls.lm.control(maxiter = 500))


km_df <- km_df |> 
  mutate(
    preds_weibull = exp(- (coef(weibull_fit)["lambda"] * tenure) ^ coef(weibull_fit)["kappa"]),
    preds_loglogis = 1 / (1 + (coef(loglogistic_fit)["lambda"] * tenure) ^ coef(loglogistic_fit)["kappa"]),
    preds_exponential_decay = exp(-coef(exp_fit)["lambda"] * tenure),
    preds_wei_exp = coef(wei_exp_fit)["p"] * exp(-coef(wei_exp_fit)["lambda_e"] * tenure) +
                        (1 - coef(wei_exp_fit)["p"]) * exp(- (coef(wei_exp_fit)["lambda_w"] * tenure) ^ coef(wei_exp_fit)["kappa_w"])

  )

```

```{r plots}

km_df_long <- km_df |> 
  filter(tenure <= 24) |> # we are only predicting out to 24 months
  pivot_longer(cols = starts_with("preds_"), names_to = "model", values_to = "prediction")

ggplot(km_df_long, aes(x = tenure)) +
  geom_line(aes(y = km_fit, color = "Actual"), linewidth = 1) +
  geom_line(aes(y = prediction, color = "Predicted"), linewidth = 3, alpha = 0.5) +
  geom_vline(aes(xintercept = 12, linetype = "train / test split"), color = "black") +
  facet_wrap(~ model, scales = "free_y") +
  ylim(0.5, NA) +
  scale_color_manual(values = c("Actual" = "steelblue", "Predicted" = "steelblue")) +
  scale_linetype_manual(values = c("train / test split" = "dashed")) +
  guides(color = guide_legend(override.aes = list(alpha = c(1, 0.5))),
         linetype = guide_legend(override.aes = list(color = "black"))) +
  theme_minimal() +
  labs(x = "Tenure", y = "Survival %", color = NULL, linetype = NULL)

```


Integrate the predictions at various cut offs for expected survival time

```{r expected_value}

mixture_params <- coef(wei_exp_fit)
p <- mixture_params["p"]
lambda_e <- mixture_params["lambda_e"]
lambda_w <- mixture_params["lambda_w"]
kappa_w <- mixture_params["kappa_w"]

mixture_survival <- function(t) {
  p * exp(-lambda_e * t) + (1 - p) * exp(- (lambda_w * t) ^ kappa_w)
}

cutoffs <- c(24, 36, 48, 60)

expected_df <- tibble(
  Cutoff = cutoffs,
  Mixture_Expected_Avg_Survival = map_dbl(cutoffs, ~ integrate(mixture_survival, lower = 0, upper = .x)$value) |> round(2)
)

expected_df |> datatable(options = list(dom = 't' ))

```